### ISSUE TITLE
Make build meta-information available in build

### ISSUE THREAD

**Issue by matthiasbeyer** [science-computing/butido#7]
This might hurt reusability if meta-information is interpolated into the packaging script (e.g. date), but maybe it is worth considering making such metadata available.

For example:

* Date
* "root" package of the build

more?

**Comment by christophprokop** [comment]
related to #337 but this issue does not provide more info/requests

**Comment by primeos-work** [comment]
I don't think this is related to the other issue. #337 is about supporting metapackages (a special kind of package) while this issue seems to be about making meta-information available to packages (during the build).

I assume that we currently don't need this feature though (apart from maybe `SOURCE_DATE_EPOCH` for #349).
